// PMS Toolkit - Master Scenario Data
// Version 3.1 - 6 Scenarios (High-Growth Tech Startup enriched with full 9-Box distribution)
// Last updated: Apr 23, 2026
// Total employees: 300 (6 scenarios × 50)
// Manufacturing Firm RecordId: recAXwhOxEFGqJGJ6

window.PMS_MASTER_DATA = {
  "version": "3.0",
  "lastUpdated": "2026-02-26",
  "scenarios": {
    "High-Growth Tech Startup": {
      "name": "High-Growth Tech Startup",
      "currency": "USD",
      "currencySymbol": "$",
      "budgetPercent": 10,
      "recordId": "recFOxRBFHIT0az8u",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Sarah Chen",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.92,
          "salary": 220000,
          "incrementPct": 15.0,
          "placement": "Star",
          "flightRisk": "High",
          "okrScore": 0.88,
          "department": "Engineering",
          "role": "Principal Engineer"
        },
        {
          "name": "Marcus Johnson",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.91,
          "salary": 200000,
          "incrementPct": 15.0,
          "placement": "Star",
          "flightRisk": "Medium",
          "okrScore": 0.85,
          "department": "Product",
          "role": "Senior Product Manager"
        },
        {
          "name": "Priya Sharma",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 195000,
          "incrementPct": 15.0,
          "placement": "Star",
          "flightRisk": "Low",
          "okrScore": 0.82,
          "department": "Engineering",
          "role": "Staff Engineer"
        },
        {
          "name": "James Mitchell",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.93,
          "salary": 185000,
          "incrementPct": 15.0,
          "placement": "Star",
          "flightRisk": "High",
          "okrScore": 0.91,
          "department": "Sales",
          "role": "Head of Enterprise Sales"
        },
        {
          "name": "Emily Rodriguez",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.65,
          "salary": 190000,
          "incrementPct": 12.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.86,
          "department": "Engineering",
          "role": "Senior Engineer"
        },
        {
          "name": "David Kim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.68,
          "salary": 175000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.79,
          "department": "Marketing",
          "role": "VP Marketing"
        },
        {
          "name": "Lisa Wang",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.62,
          "salary": 165000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.77,
          "department": "Engineering",
          "role": "Engineering Manager"
        },
        {
          "name": "Ryan O'Connor",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.64,
          "salary": 155000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.81,
          "department": "Product",
          "role": "Product Manager"
        },
        {
          "name": "Jasmine Lee",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.67,
          "salary": 148000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.76,
          "department": "Sales",
          "role": "Senior Account Executive"
        },
        {
          "name": "Alex Morgan",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.63,
          "salary": 142000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Medium",
          "okrScore": 0.74,
          "department": "Engineering",
          "role": "Senior Engineer"
        },
        {
          "name": "Mia Thompson",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.61,
          "salary": 138000,
          "incrementPct": 10.0,
          "placement": "High Performer",
          "flightRisk": "Low",
          "okrScore": 0.72,
          "department": "Design",
          "role": "Lead Designer"
        },
        {
          "name": "Brandon Hall",
          "perfRating": 5.0,
          "potRating": 1.0,
          "perfScore": 3.5,
          "potScore": 0.35,
          "salary": 235000,
          "incrementPct": 8.0,
          "placement": "Trusted Pro",
          "flightRisk": "Low",
          "okrScore": 0.84,
          "department": "Engineering",
          "role": "Principal Architect"
        },
        {
          "name": "Rachel Green",
          "perfRating": 4.0,
          "potRating": 1.0,
          "perfScore": 2.8,
          "potScore": 0.32,
          "salary": 178000,
          "incrementPct": 7.0,
          "placement": "Trusted Pro",
          "flightRisk": "Low",
          "okrScore": 0.78,
          "department": "Finance",
          "role": "Head of Finance"
        },
        {
          "name": "Tyler Scott",
          "perfRating": 4.0,
          "potRating": 1.0,
          "perfScore": 2.8,
          "potScore": 0.38,
          "salary": 162000,
          "incrementPct": 7.0,
          "placement": "Trusted Pro",
          "flightRisk": "Low",
          "okrScore": 0.75,
          "department": "Engineering",
          "role": "Senior DevOps Engineer"
        },
        {
          "name": "Amanda Foster",
          "perfRating": 4.0,
          "potRating": 1.0,
          "perfScore": 2.8,
          "potScore": 0.31,
          "salary": 155000,
          "incrementPct": 7.0,
          "placement": "Trusted Pro",
          "flightRisk": "Low",
          "okrScore": 0.73,
          "department": "Sales",
          "role": "Senior Customer Success Manager"
        },
        {
          "name": "Kevin Lee",
          "perfRating": 4.0,
          "potRating": 1.0,
          "perfScore": 2.8,
          "potScore": 0.34,
          "salary": 148000,
          "incrementPct": 7.0,
          "placement": "Trusted Pro",
          "flightRisk": "Low",
          "okrScore": 0.71,
          "department": "Marketing",
          "role": "Senior Marketing Manager"
        },
        {
          "name": "Isabella Cruz",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.88,
          "salary": 135000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "Medium",
          "okrScore": 0.65,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Noah Price",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.91,
          "salary": 128000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "High",
          "okrScore": 0.62,
          "department": "Product",
          "role": "Associate Product Manager"
        },
        {
          "name": "Zara Ahmed",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.89,
          "salary": 122000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "Medium",
          "okrScore": 0.67,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Lucas Bailey",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.87,
          "salary": 118000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "Low",
          "okrScore": 0.64,
          "department": "Sales",
          "role": "Account Executive"
        },
        {
          "name": "Chloe Adams",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 115000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "Medium",
          "okrScore": 0.61,
          "department": "Marketing",
          "role": "Marketing Manager"
        },
        {
          "name": "Ethan Clark",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.86,
          "salary": 112000,
          "incrementPct": 8.0,
          "placement": "Core Performer",
          "flightRisk": "Low",
          "okrScore": 0.63,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Grace Ho",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.65,
          "salary": 125000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.71,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Daniel Edwards",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.62,
          "salary": 118000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.68,
          "department": "Sales",
          "role": "Account Executive"
        },
        {
          "name": "Olivia Brown",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.64,
          "salary": 112000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.69,
          "department": "Engineering",
          "role": "QA Engineer"
        },
        {
          "name": "Benjamin Chan",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.61,
          "salary": 108000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.66,
          "department": "Product",
          "role": "Product Analyst"
        },
        {
          "name": "Sophia Brown",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.63,
          "salary": 105000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.67,
          "department": "Marketing",
          "role": "Content Manager"
        },
        {
          "name": "Mason Wright",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.66,
          "salary": 102000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.7,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Hannah Lewis",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 99000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.65,
          "department": "Sales",
          "role": "Sales Development Rep"
        },
        {
          "name": "Oscar Collins",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.67,
          "salary": 96000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.68,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Ruby Stewart",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.62,
          "salary": 94000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.64,
          "department": "Design",
          "role": "UX Designer"
        },
        {
          "name": "Charlie Wood",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.61,
          "salary": 92000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.63,
          "department": "Marketing",
          "role": "Growth Analyst"
        },
        {
          "name": "Lily Campbell",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.64,
          "salary": 90000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.66,
          "department": "Engineering",
          "role": "Junior Engineer"
        },
        {
          "name": "Max Ward",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.63,
          "salary": 90000,
          "incrementPct": 5.0,
          "placement": "Solid Performer",
          "flightRisk": "Low",
          "okrScore": 0.65,
          "department": "Product",
          "role": "Junior Product Manager"
        },
        {
          "name": "Jordan Kim",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.38,
          "salary": 132000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.58,
          "department": "Engineering",
          "role": "Senior Engineer"
        },
        {
          "name": "Natalie Brooks",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.35,
          "salary": 124000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.55,
          "department": "Sales",
          "role": "Account Manager"
        },
        {
          "name": "Samuel Adams",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.32,
          "salary": 118000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.52,
          "department": "Marketing",
          "role": "Marketing Specialist"
        },
        {
          "name": "Victoria Hill",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.36,
          "salary": 112000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.54,
          "department": "Engineering",
          "role": "QA Engineer"
        },
        {
          "name": "Patrick Moore",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.33,
          "salary": 105000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.51,
          "department": "Product",
          "role": "Product Analyst"
        },
        {
          "name": "Dorothy Hall",
          "perfRating": 3.0,
          "potRating": 1.0,
          "perfScore": 2.1,
          "potScore": 0.31,
          "salary": 98000,
          "incrementPct": 3.0,
          "placement": "Inconsistent",
          "flightRisk": "Low",
          "okrScore": 0.49,
          "department": "Sales",
          "role": "Sales Development Rep"
        },
        {
          "name": "Aisha Mohammed",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 95000,
          "incrementPct": 4.0,
          "placement": "Emerging Talent",
          "flightRisk": "High",
          "okrScore": 0.48,
          "department": "Engineering",
          "role": "Software Engineer"
        },
        {
          "name": "Carlos Mendoza",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.88,
          "salary": 90000,
          "incrementPct": 4.0,
          "placement": "Emerging Talent",
          "flightRisk": "Medium",
          "okrScore": 0.45,
          "department": "Product",
          "role": "Associate Product Manager"
        },
        {
          "name": "Yuki Nakamura",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.91,
          "salary": 88000,
          "incrementPct": 4.0,
          "placement": "Emerging Talent",
          "flightRisk": "High",
          "okrScore": 0.42,
          "department": "Engineering",
          "role": "Junior Engineer"
        },
        {
          "name": "Leila Rahman",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.89,
          "salary": 85000,
          "incrementPct": 4.0,
          "placement": "Emerging Talent",
          "flightRisk": "Medium",
          "okrScore": 0.44,
          "department": "Marketing",
          "role": "Marketing Coordinator"
        },
        {
          "name": "Chris Peterson",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.62,
          "salary": 118000,
          "incrementPct": 2.0,
          "placement": "Question Mark",
          "flightRisk": "Medium",
          "okrScore": 0.41,
          "department": "Engineering",
          "role": "Senior Engineer"
        },
        {
          "name": "Diana Foster",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.64,
          "salary": 108000,
          "incrementPct": 2.0,
          "placement": "Question Mark",
          "flightRisk": "Low",
          "okrScore": 0.38,
          "department": "Sales",
          "role": "Account Executive"
        },
        {
          "name": "Eugene Teo",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.61,
          "salary": 98000,
          "incrementPct": 2.0,
          "placement": "Question Mark",
          "flightRisk": "Medium",
          "okrScore": 0.36,
          "department": "Marketing",
          "role": "Marketing Analyst"
        },
        {
          "name": "Fiona Koh",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.63,
          "salary": 90000,
          "incrementPct": 2.0,
          "placement": "Question Mark",
          "flightRisk": "Low",
          "okrScore": 0.39,
          "department": "Engineering",
          "role": "Junior Engineer"
        },
        {
          "name": "Gary Phillips",
          "perfRating": 1.0,
          "potRating": 1.0,
          "perfScore": 0.7,
          "potScore": 0.28,
          "salary": 142000,
          "incrementPct": 0.0,
          "placement": "Low Performer",
          "flightRisk": "Low",
          "okrScore": 0.22,
          "department": "Sales",
          "role": "Senior Account Executive"
        },
        {
          "name": "Helen Morris",
          "perfRating": 2.0,
          "potRating": 1.0,
          "perfScore": 1.4,
          "potScore": 0.31,
          "salary": 95000,
          "incrementPct": 0.0,
          "placement": "Low Performer",
          "flightRisk": "Low",
          "okrScore": 0.28,
          "department": "Marketing",
          "role": "Marketing Specialist"
        }
      ]
    }    },
    "Professional Services Firm": {
      "name": "Professional Services Firm",
      "currency": "GBP",
      "currencySymbol": "£",
      "budgetPercent": 8,
      "recordId": "rectobtZt42HMeQPD",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Oliver Thompson",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 180000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Charlotte Davies",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 175000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Henry Wilson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 165000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Amelia Brown",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 155000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "George Taylor",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 150000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Sophie Anderson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 140000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "William Harris",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 142000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Isabella Martin",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 135000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "James Robinson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 138000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Emily Walker",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 141000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Benjamin White",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 125000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Mia Hughes",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 127000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Alexander Clark",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 115000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Grace Lewis",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 118000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Daniel Edwards",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 110000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Scarlett Green",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 112000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Samuel Adams",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 120000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Poppy Mitchell",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 108000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Thomas Baker",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 105000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Lily Campbell",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 102000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Edward Phillips",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 118000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Freya Turner",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 115000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Oscar Collins",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 117000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Ruby Stewart",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 114000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Arthur Morris",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 108000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Isla Murphy",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 110000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Leo Rogers",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 105000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Evie Cook",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 107000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Noah Price",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 103000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Elsie Bell",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 100000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Charlie Wood",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 95000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Ava Barnes",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 92000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Freddie Scott",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 90000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Ivy Cooper",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 93000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Archie Gray",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 88000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Daisy Richardson",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 96000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Alfie Watson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 91000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Florence Howard",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 85000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Max Ward",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 87000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Matilda Brooks",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 89000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Harrison Kelly",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 94000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Rosie Sanders",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 82000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Lucas Bailey",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 86000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Sienna Foster",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 95000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Sebastian Russell",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 75000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Esme Griffin",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 77000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Hugo Simmons",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 74000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Phoebe Webb",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 70000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Theodore Hunt",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 76000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Beatrice Palmer",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 75000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        }
      ]
    },
    "Enterprise Healthcare": {
      "name": "Enterprise Healthcare",
      "currency": "USD",
      "currencySymbol": "$",
      "budgetPercent": 4,
      "recordId": "recawJssrebQBLd8W",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Dr. Patricia Reynolds",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 250000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Michael Chang",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 245000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Jennifer Martinez",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 230000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Robert Jackson",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 220000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Sarah Williams",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 215000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "David Thompson",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 185000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Lisa Anderson",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 180000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. James Peterson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 195000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Maria Rodriguez",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 175000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Thomas Wright",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 170000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Emily Davis",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 165000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Christopher Lee",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 155000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Angela Moore",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 150000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Kevin Harris",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 145000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Rachel Green",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 160000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Steven Baker",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 135000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Michelle Turner",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 130000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Daniel White",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 120000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Karen Scott",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 118000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Andrew Miller",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 140000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Sandra Collins",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 125000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Paul Martinez",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 115000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Nancy Adams",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 112000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Brian Nelson",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 108000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Laura King",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 105000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Jessica Taylor",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 175000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Richard Brown",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 172000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Margaret Wilson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 145000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Joseph Garcia",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 155000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Elizabeth Clark",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 132000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "William Anderson",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 118000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Carol Phillips",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 130000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "George Martinez",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 115000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dr. Helen Parker",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 158000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Kenneth Lewis",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 112000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Dorothy Hall",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 95000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Charles Young",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 92000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Betty Allen",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 96000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Frank Robinson",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 88000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Ruth Walker",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 85000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Raymond Torres",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 87000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Virginia Hill",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 94000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Gregory Campbell",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 90000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Donna Mitchell",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 95000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Ronald Roberts",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 82000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Deborah Carter",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 93000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Gary Phillips",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 80000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Sharon Evans",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 78000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Larry Turner",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 79000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        },
        {
          "name": "Barbara Collins",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 91000,
          "incrementPct": 2.4,
          "placement": "Question Mark"
        }
      ]
    },
    "Remote-First SaaS": {
      "name": "Remote-First SaaS",
      "currency": "USD",
      "currencySymbol": "$",
      "budgetPercent": 10,
      "recordId": "reciXFyWH9LBluwgX",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Alex Morgan",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 180000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Maya Patel",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 165000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Carlos Silva",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 155000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Elena Volkov",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 150000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Jamal Williams",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 145000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Sofia Andersson",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 140000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Hiroshi Tanaka",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 135000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Aisha Ibrahim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 125000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Luca Rossi",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 130000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Priya Sharma",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 128000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Marco Santos",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 118000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Yuki Nakamura",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 115000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Omar Hassan",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 112000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Nina Kowalski",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 110000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Diego Martinez",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 108000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Leila Rahman",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 105000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Anton Petrov",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 103000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Fatima Al-Said",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 100000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Kim Min-jun",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 102000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Isabella Garcia",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 98000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Raj Kumar",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 125000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Emma Wilson",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 122000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Chen Wei",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 128000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Zara Ahmed",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 120000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Lars Nielsen",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 108000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Ana Popescu",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 110000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Ahmed Khalil",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 105000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Maria Gonzalez",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 102000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Kenji Sato",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 107000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Olivia Brown",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 109000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Andrei Volkov",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 95000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Camila Fernandez",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 92000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Hassan Osman",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 90000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Julia Schmidt",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 93000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Rafael Costa",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 88000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Mira Novak",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 91000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Tariq Mansoor",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 87000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Natasha Ivanova",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 89000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Luis Ramirez",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 90000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Sana Khan",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 86000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Dimitri Papadopoulos",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 92000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Alina Petrova",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 85000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Viktor Horvath",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 88000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Yasmin Al-Farsi",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 84000,
          "incrementPct": 13.0,
          "placement": "High Performer"
        },
        {
          "name": "Paolo Bianchi",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 89000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Kira Johansson",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 75000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Mateo Vargas",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 72000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Amara Diop",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 70000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Tomas Novotny",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 73000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        },
        {
          "name": "Nia Williams",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 74000,
          "incrementPct": 6.0,
          "placement": "Question Mark"
        }
      ]
    },
    "Financial Services": {
      "name": "Financial Services",
      "currency": "SGD",
      "currencySymbol": "S$",
      "budgetPercent": 8,
      "recordId": "recLbFTZGyAPUdOvg",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Richard Tan",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 320000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Catherine Lim",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 300000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Michael Wong",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 285000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Priya Menon",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 270000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "David Chen",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 260000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Sarah Kumar",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 255000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Jonathan Ng",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 250000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Angela Tan",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 245000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Vincent Lee",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 230000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Grace Ho",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 228000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Raymond Koh",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 225000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Michelle Chong",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 220000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Daniel Teo",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 218000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Melissa Yap",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 210000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Kenneth Lim",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 205000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Jessica Chua",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 195000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "William Goh",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 198000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Christina Ng",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 192000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Marcus Tan",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 188000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Stephanie Ong",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 180000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Aaron Loh",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 175000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Rachel Sim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 172000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Bryan Koh",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 170000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Emily Tan",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 165000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Nicholas Wong",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 185000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Vivian Lee",
          "perfRating": 5.0,
          "potRating": 3.0,
          "perfScore": 3.5,
          "potScore": 0.9,
          "salary": 182000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Jeremy Tay",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 180000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Samantha Lim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 178000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Benjamin Chan",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 165000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Natalie Yeo",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 162000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Adrian Poh",
          "perfRating": 5.0,
          "potRating": 2.0,
          "perfScore": 3.5,
          "potScore": 0.6,
          "salary": 160000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Vanessa Ng",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 158000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Ryan Seah",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 152000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Claire Tan",
          "perfRating": 4.0,
          "potRating": 3.0,
          "perfScore": 2.8,
          "potScore": 0.9,
          "salary": 159000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Derek Lim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 155000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Fiona Koh",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 145000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Eugene Teo",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 142000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Jasmine Lee",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 143000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Kevin Ong",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 140000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Linda Chen",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 135000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Mark Tan",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 141000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Nicole Goh",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 138000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Oliver Ng",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 139000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Patricia Lim",
          "perfRating": 4.0,
          "potRating": 2.0,
          "perfScore": 2.8,
          "potScore": 0.6,
          "salary": 142000,
          "incrementPct": 10.4,
          "placement": "High Performer"
        },
        {
          "name": "Quincy Tay",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 128000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Rebecca Ho",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 132000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Steven Wong",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 130000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Tiffany Yap",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 133000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Victor Koh",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 129000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        },
        {
          "name": "Wendy Tan",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 125000,
          "incrementPct": 4.8,
          "placement": "Question Mark"
        }
      ]
    },
    "Manufacturing Firm": {
      "name": "Manufacturing Firm",
      "currency": "EUR",
      "currencySymbol": "€",
      "budgetPercent": 3,
      "recordId": "recAXwhOxEFGqJGJ6",
      "employeeCount": 50,
      "employees": [
        {
          "name": "Hans Schmitt",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 44133,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Sabine Schmidt",
          "perfRating": 1.0,
          "potRating": 3.0,
          "perfScore": 0.7,
          "potScore": 0.9,
          "salary": 43166,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Claudia SchrÃ¶der",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 42433,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Stefanie SchÃ¤fer",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Gabriele Richter",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 44333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Frank Weber",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43833,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Klaus MÃ¼ller",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 44333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Frank SchÃ¤fer",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 42933,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Andreas Lange",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 44500,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Peter SchrÃ¶der",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43933,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Sabine Hoffmann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43433,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Tobias Lehmann",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 43633,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Andreas Wagner",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43133,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Nicole Hoffmann",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 44300,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "JÃ¼rgen Hofmann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 43833,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Simone SchrÃ¶der",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 44333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Alexander Werner",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 42833,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Matthias Schmidt",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 43800,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Stefan Krause",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 42933,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Florian Bauer",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 43333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Wolfgang Hoffmann",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 57600,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Alexander Werner",
          "perfRating": 1.0,
          "potRating": 2.0,
          "perfScore": 0.7,
          "potScore": 0.6,
          "salary": 58000,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Christina Meier",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 59000,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Julia Hartmann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 57950,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Thomas Weber",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 57200,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Klaus Lange",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 59000,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Sebastian Hoffmann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 58100,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Daniel Schmitz",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 58400,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Anna SchrÃ¶der",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 59400,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Frank Schmitt",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 57200,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Andrea Wolf",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 59000,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Wolfgang Hofmann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 59000,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Martin Neumann",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 56450,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Frank SchÃ¤fer",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 58700,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Michael Koch",
          "perfRating": 3.0,
          "potRating": 2.0,
          "perfScore": 2.1,
          "potScore": 0.6,
          "salary": 59100,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Wolfgang Braun",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 72466,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Peter Weber",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 71266,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Tobias KrÃ¼ger",
          "perfRating": 1.0,
          "potRating": 3.0,
          "perfScore": 0.7,
          "potScore": 0.9,
          "salary": 71533,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Susanne Hartmann",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 71866,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Stefanie Schmid",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 72066,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Alexander Schulz",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 71666,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Christian Koch",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 73266,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Gabriele Lehmann",
          "perfRating": 1.0,
          "potRating": 3.0,
          "perfScore": 0.7,
          "potScore": 0.9,
          "salary": 69333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Karin KrÃ¼ger",
          "perfRating": 2.0,
          "potRating": 3.0,
          "perfScore": 1.4,
          "potScore": 0.9,
          "salary": 73066,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Birgit Lehmann",
          "perfRating": 3.0,
          "potRating": 3.0,
          "perfScore": 2.1,
          "potScore": 0.9,
          "salary": 74200,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Hans Bauer",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 91266,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Maria Schmidt",
          "perfRating": 1.0,
          "potRating": 2.0,
          "perfScore": 0.7,
          "potScore": 0.6,
          "salary": 91733,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Christian Braun",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 90066,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Christian Schulz",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 115833,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        },
        {
          "name": "Simone Schmitt",
          "perfRating": 2.0,
          "potRating": 2.0,
          "perfScore": 1.4,
          "potScore": 0.6,
          "salary": 118333,
          "incrementPct": 1.8,
          "placement": "Question Mark"
        }
      ]
    }
  }
};

window.getScenarioByRecordId = function(recordId) {
  for (var scenarioName in window.PMS_MASTER_DATA.scenarios) {
    var scenario = window.PMS_MASTER_DATA.scenarios[scenarioName];
    if (scenario.recordId === recordId) {
      return scenario;
    }
  }
  return null;
};

window.getScenarioByName = function(name) {
  return window.PMS_MASTER_DATA.scenarios[name] || null;
};
